/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models\girlAnimation.glb 
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useCharacterAnimations } from "../Contexts/CharacterAnimations";

export function NewGirl(props: any) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "./models/girlAnimation.glb",
  );
  const { actions, names } = useAnimations(animations, group);

  const { setAnimations, animationIndex } = useCharacterAnimations();

  useEffect(() => {
    console.log(names);
    setAnimations(names);
  }, [names, setAnimations]);

  useEffect(() => {
    if (
      names &&
      names.length > 0 &&
      actions &&
      actions[names[animationIndex]]
    ) {
      actions[names[animationIndex]]!.reset().fadeIn(1).play();
      return () => {
        actions[names[animationIndex]]!.fadeOut(1);
      };
    }
  }, [animationIndex, actions, names]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Talking" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh
            name="Erika_Archer_Body_Mesh"
            geometry={nodes.Erika_Archer_Body_Mesh.geometry}
            material={materials.Akai_MAT}
            skeleton={nodes.Erika_Archer_Body_Mesh.skeleton}
          />
          <skinnedMesh
            name="Erika_Archer_Clothes_Mesh"
            geometry={nodes.Erika_Archer_Clothes_Mesh.geometry}
            material={materials.eyelash_MAT}
            skeleton={nodes.Erika_Archer_Clothes_Mesh.skeleton}
          />
          <skinnedMesh
            name="Erika_Archer_Eyelashes_Mesh"
            geometry={nodes.Erika_Archer_Eyelashes_Mesh.geometry}
            material={materials.Body_MAT}
            skeleton={nodes.Erika_Archer_Eyelashes_Mesh.skeleton}
          />
          <skinnedMesh
            name="Erika_Archer_Eyes_Mesh"
            geometry={nodes.Erika_Archer_Eyes_Mesh.geometry}
            material={materials.EyeSpec_MAT}
            skeleton={nodes.Erika_Archer_Eyes_Mesh.skeleton}
          />
        </group>
        <group name="Dying" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips_1} />
        </group>
        <group name="Jump" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips_2} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./models/girlAnimation.glb");
