"use client";
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models\woman.gltf 
*/
import { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useCharacterAnimations } from "../Contexts/CharacterAnimations";

const Woman = (props: any) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("./models/woman.gltf");
  const { actions, names } = useAnimations(animations, group);
  const { setAnimations, animationIndex } = useCharacterAnimations();
  useEffect(() => {
    setAnimations(names);
  }, [names, setAnimations]);

  useEffect(() => {
    if (
      names &&
      names.length > 0 &&
      actions &&
      actions[names[animationIndex]]
    ) {
      actions[names[animationIndex]]!.reset().fadeIn(0.5).play();
      return () => {
        actions[names[animationIndex]]!.fadeOut(0.5);
      };
    }
  }, [animationIndex, actions, names]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <group name="SM_Chr_Developer_Female_02">
            <skinnedMesh
              castShadow
              name="Mesh019"
              geometry={(nodes.Mesh019 as THREE.SkinnedMesh).geometry}
              material={materials.Glasses}
              skeleton={(nodes.Mesh019 as THREE.SkinnedMesh).skeleton}
            />
            <skinnedMesh
              castShadow
              name="Mesh019_1"
              geometry={(nodes.Mesh019_1 as THREE.SkinnedMesh).geometry}
              material={materials.Eyes}
              skeleton={(nodes.Mesh019_1 as THREE.SkinnedMesh).skeleton}
            />
            <skinnedMesh
              castShadow
              name="Mesh019_2"
              geometry={(nodes.Mesh019_2 as THREE.SkinnedMesh).geometry}
              material={materials.Hair}
              skeleton={(nodes.Mesh019_2 as THREE.SkinnedMesh).skeleton}
            />
            <skinnedMesh
              castShadow
              name="Mesh019_3"
              geometry={(nodes.Mesh019_3 as THREE.SkinnedMesh).geometry}
              material={materials.Skin}
              skeleton={(nodes.Mesh019_3 as THREE.SkinnedMesh).skeleton}
            />
            <skinnedMesh
              castShadow
              name="Mesh019_4"
              geometry={(nodes.Mesh019_4 as THREE.SkinnedMesh).geometry}
              material={materials.Mouth}
              skeleton={(nodes.Mesh019_4 as THREE.SkinnedMesh).skeleton}
            />
            <skinnedMesh
              castShadow
              name="Mesh019_5"
              geometry={(nodes.Mesh019_5 as THREE.SkinnedMesh).geometry}
              material={materials.Shirt}
              skeleton={(nodes.Mesh019_5 as THREE.SkinnedMesh).skeleton}
            />
            <skinnedMesh
              castShadow
              name="Mesh019_6"
              geometry={(nodes.Mesh019_6 as THREE.SkinnedMesh).geometry}
              material={materials.Pants}
              skeleton={(nodes.Mesh019_6 as THREE.SkinnedMesh).skeleton}
            />
            <skinnedMesh
              castShadow
              name="Mesh019_7"
              geometry={(nodes.Mesh019_7 as THREE.SkinnedMesh).geometry}
              material={materials.Shoes}
              skeleton={(nodes.Mesh019_7 as THREE.SkinnedMesh).skeleton}
            />
            <skinnedMesh
              castShadow
              name="Mesh019_8"
              geometry={(nodes.Mesh019_8 as THREE.SkinnedMesh).geometry}
              material={materials.Sole}
              skeleton={(nodes.Mesh019_8 as THREE.SkinnedMesh).skeleton}
            />
            <skinnedMesh
              castShadow
              name="Mesh019_9"
              geometry={(nodes.Mesh019_9 as THREE.SkinnedMesh).geometry}
              material={materials.Laces}
              skeleton={(nodes.Mesh019_9 as THREE.SkinnedMesh).skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
};

export default Woman;

useGLTF.preload("./models/woman.gltf");
